info/urls.py
from django.urls import path
from . import views
# from .views import info_index

app_name = "info"
urlpatterns = [
    path('', views.ShopIndecView.as_view(), name="info_index"),
    path("groups/", views.GroupsListView.as_view(), name="groups_list"),
    path("products/", views.ProductsListView.as_view(), name="products_list"),
    path("products/export", views.ProductsDataExportView.as_view(), name="products-export"),

    path("products/create", views.ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", views.ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update", views.ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-delete", views.ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", views.OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>/", views.OrdersDetailView.as_view(), name="order_details"),
]

info_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [

    path('admin/', admin.site.urls),
    path('info/', include('info.urls')),
    path('map/', include('map_data.urls')),
    path('myauth/', include('myauth.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

info/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    # @property
    # def description_short(self) -> str:
    #     if len(self.description)<48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"

def product_images_directory_path(instance: 'ProductImage', filename:str) -> str:
    return "product/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)

class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts')

info/forms.py
from django import forms
from django.core import validators
from .models import Product

from django.contrib.auth.models import Group
from django.forms import ModelForm


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
    )
# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000, decimal_places=2)
#     description = forms.CharField(
#         label="Product description",
#         widget=forms.Textarea(attrs={"rows": 5, "cols": "50"}),
#         validators=[validators.RegexValidator(
#             regex=r"great",
#             message="Field must contain word 'great'"
#         )],
#     )

info/views.py
from itertools import product

from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from timeit import default_timer
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Product, Order, ProductImage
# from .forms import ProductForm
from .forms import GroupForm, ProductForm
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin


class ShopIndecView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('laptop', 1999),
            ('Desc', 299),
            ('Smartphone', 4564),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,

        }
        return render(request, 'info/info-st.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm,
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'info/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = "info/product-details.html"
    # model = Product
    queryset = Product.objects.prefetch_related('images'),
    context_object_name = "product"
    queryset = Product.objects.filter(archived=False)


class ProductsListView(ListView):
    template_name = "info/products-list.html"
    model = Product
    context_object_name = "products"


# def create_product(request: HttpRequest) -> HttpResponse:
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             # name = form.cleaned_data["name"]
#             # price = form.cleaned_data["price"]
#             # Product.objects.create(**form.cleaned_data)
#             form.save()
#             url = reverse("info:products_list")
#             return redirect(url)
#     else:
#         form = ProductForm()
#     context = {
#         "form": form,
#     }
#
#     return render(request, 'info/create-product.html', context=context)

class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        return self.request.user.is_superuser

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy('info:products_list')


class ProductUpdateView(UpdateView):
    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            "info:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("info:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects.select_related("user").prefetch_related('products')
    )


class OrdersDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ["info:view_order"]

    queryset = (
        Order.objects.select_related("user").prefetch_related('products')
    )


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]
        return JsonResponse({"products": products_data})

info/templates/info/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base title
        {% endblock %}
    </title>
</head>
<body>
        {% block body %}
        Base body
        {% endblock %}

<div>
    {% now 'H:i' %}
</div>
</body>
</html>

info/templates/info/create-product.html
{% extends 'info/base.html' %}

{% block title %}
Create product
{% endblock %}

{% block body %}


<h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">CREATE</button>
        </form>


    </div>

<div>
    <a href="{% url 'info:products_list' %}">Back to products list</a>
</div>

{% endblock %}

info/templates/info/groups-list.html
{% extends 'info/base.html' %}

{% block title %}
Groups list
{% endblock %}

{% block body %}
<h1>Groups:</h1>

<div>
        <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                        Create
                </button>
        </form>
</div>

<div>
        <ul>
        {% for gr in groups %}
        <li>
                <div>{{ gr.name }}</div>
                <ul>
                        {% for permission in gr.permissions.all %}
                        <li>{{ permission.name }}
                        (<code>{{ permission.codename }}</code>)
                        </li>
                        {% endfor %}

                </ul>
        </li>
        {% empty%}
        No No NO NO nO
        {% endfor %}
    </ul>
</div>
{% endblock %}

info/templates/info/info-st.html
{% extends 'info/base.html' %}

{% block title %}
Ingo index222
{% endblock %}


{% block body %}

<div>
    <ul>
        {% for name, price in products%}
        <li>{{ name }} for ${{ price }}</li>
        {% empty%}
        No No NO NO nO
        {% endfor %}
    </ul>
</div>



<div>
    time Running : {{ time_running }}
</div>

<div>
    {% lorem %}
</div>
{% endblock %}

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>ghhghg</title>-->
<!--</head>-->
<!--<body>-->
<!--<h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaa</h1>-->
<!--<div>-->
<!--    time Running : {{ time_running }}-->
<!--</div>-->

<!--<div>-->
<!--    {% lorem %}-->
<!--</div>-->

<!--</body>-->
<!--</html>-->

info/templates/info/order_detail.html
{% extends 'info/base.html' %}

{% block title %}
Order #{{ object.pk }} details
{% endblock %}


{% block body %}
<h1>ORDER #{{ object.pk }}</h1>


 <div>
            <p>{% firstof object.user.first_name object.user.username %}</p>
            <p>Promocode: <code> {{object.promocode }} </code></p>
            <p>Delivery: <code> {{object.delivery_address }} </code></p>
        </div>
        <div>Products in order:</div>
        <ul>
            {% for foo in object.products.all %}
            <li>
                {{ foo.name }} for ${{ foo.price }}
            </li>
            {% endfor%}
        </ul>

    </div>


<div>
    <a href="{% url 'info:orders_list' %}">Back to orders</a>>
</div>

{% endblock %}

info/templates/info/order_list.html
{% extends 'info/base.html' %}

{% block title %}
Orders list
{% endblock %}


{% block body %}
<h1>ORDERS list</h1>

{% if object_list %}

    <div>
        {% for order in object_list %}
        <div>

            <p><a href="{% url 'info:order_details' pk=order.pk %}">Details #{{order.pk}}</a> </p>
            <p>{% firstof order.user.first_name order.user.username %}</p>
            <p>Promocode: <code> {{order.promocode }} </code></p>
            <p>Delivery: <code> {{order.delivery_address }} </code></p>
        </div>
        <div>Products in order:</div>
        <ul>
            {% for foo in order.products.all %}
            <li>
                {{ foo.name }} for ${{ foo.price }}
            </li>
            {% endfor%}
        </ul>
        {% endfor %}
    </div>

    {% else %}
    <h3>no orders</h3>
    {% endif %}


{% endblock %}

info/templates/info/orders-list.html
{% extends 'info/base.html' %}

{% block title %}
Orders list
{% endblock %}


{% block body %}
<h1>ORDERS list</h1>

{% if orders%}

    <div>
        {% for order in orders %}
        <div>
            <p>{% firstof order.user.first_name order.user.username %}</p>
            <p>Promocode: <code> {{order.promocode }} </code></p>
            <p>Delivery: <code> {{order.delivery_address }} </code></p>
        </div>
        <div>Products in order:</div>
        <ul>
            {% for foo in order.products.all %}
            <li>
                {{ foo.name }} for ${{ foo.price }}
            </li>
            {% endfor%}
        </ul>
        {% endfor %}
    </div>

    {% else %}
    <h3>no orders</h3>
    {% endif %}


{% endblock %}

info/templates/info/product-details.html
{% extends 'info/base.html' %}


{% block title %}
Product #{{ product.pk }}
{% endblock %}

{% block body %}
<h1>Product <strong>{{ product.name }}</strong></h1>
<div>
    <div>Description: <em> {{ product.description }} </em> </div>
    <div>Price: {{ product.price }} </div>
    <div>Discount: {{ product.discount }} </div>
    <div>Archived: {{ product.archived }} </div>

                {% if product.preview %}
                <img src="{{product.preview.url }}" alt="{{ product.preview.name }}">
            {% endif %}

    <h3>IMAGES</h3>
    <div>
        {% for img in product.images.all %}
        <div>
            <img src="{{ img.image.url }}" alt="{{ img.image.name}}">
            <div>
                {{ img.description }}
            </div>
        </div>
            {% empty %}
                <div>
                    No images uploaded yet
                </div>
        {% endfor %}
    </div>

</div>
<div>
    <a href = "{% url 'info:product_update' pk=product.pk %}">BUpdate product</a>
</div>
<div>
    <a href = "{% url 'info:product_delete' pk=product.pk %}">Delete product</a>
</div>
<div>
    <a href = "{% url 'info:products_list' %}">BACK TO ProDUCTS LIST</a>
</div>
{% endblock %}

info/templates/info/product_confirm_delete.html
{% extends 'info/base.html' %}


{% block title %}
Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
<h1>Are you sure to delete {{ object.name }}</h1>
<br>
<div>
    <a href="{% url 'info:product_details' pk=object.pk %}">Back to product #{{ object.pk }}</a>
</div>
<br>
<div>
    <form method="post">
        {% csrf_token %}
        {{ forms.as_p}}
        <button type="submit">Delete</button>

    </form>
</div>

{% endblock %}

info/templates/info/product_form.html
{% extends 'info/base.html' %}


{% block title %}
Create product
{% endblock %}

{% block body %}
<h1>Create product</h1>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Create</button>>
    </form>
</div>

<div>
    <a href="{% url 'info:products_list' %}">Go to product list</a>
</div>

{% endblock %}

info/templates/info/product_update_form.html
{% extends 'info/base.html' %}


{% block title %}
Update product
{% endblock %}

{% block body %}
<h1>Update product</h1>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> update</button>>
    </form>
</div>

<div>
    <a href="{% url 'info:product_details' pk=object.pk %}">Go to product #{{ object.pk }}</a>
</div>

{% endblock %}

info/templates/info/products-list.html
{% extends 'info/base.html' %}

{% block title %}
Products list
{% endblock %}


{% block body %}
<h1>Products list</h1>

    {% if products%}

    <div>
        {% for prod in products%}
        <div>

            <p><a href="{% url 'info:product_details' pk=prod.pk %}">NAme: {{ prod.name}}</a></p>
            <p>price: {{ prod.price}}</p>
            <p>discount: {% firstof prod.discount 'no discount' %}</p>
            <p>created: {{ prod.created_at}}</p>
            <p>description: {{ prod.description}}</p>

            {% if product.preview %}
                <img src="{{product.preview.url }}" alt="{{ product.preview.name }}">
            {% endif %}


        </div>
        {% endfor %}
    </div>

    {% else %}
    <h3>no products</h3>
    {% endif %}

<div>
    <a href="{% url 'info:product_create' %}">Create a new product</a>
</div>

{% endblock %}